In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import yaml

In [2]:
with open("../config-local.yaml", "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

mysql_config = config["db"]
engine = create_engine(
    f"mysql+pymysql://{mysql_config['user']}:{mysql_config['password']}@{mysql_config['host']}:{mysql_config['port']}/{mysql_config['name']}?charset=utf8mb4"
)

pd.read_sql("SELECT 1 AS ok;", engine)

   ok
0   1

In [3]:
app_raw_df = pd.read_sql_table("Application", con=engine)
app_df = app_raw_df.copy()
app_df.head()

,cdate,company_uuid,job_uuid,user_uuid,application_uuid
0,2017-02-25 23:45:01,de4b3596-b4ab-47cd-b8ea-6f9e14170064,459e461d-a571-4ed3-8751-8f4cb5b9ff37,b0329bd7-fc45-4e83-993a-b73bd9d3549c,59c42363-f764-4cbd-aafd-20eb663ea5d7
1,2020-11-23 14:46:07,f6156b12-d4d7-469f-84be-31799c765211,e5ed4f4a-08aa-4f2d-9042-1e9bbd36803f,b0329bd7-fc45-4e83-993a-b73bd9d3549c,425db0e8-87f8-4b4d-8248-7f24c31d49d3
2,2017-10-28 22:30:11,2ed05b18-c735-474a-9faa-02095b25729a,0f636d7a-53f7-485e-8a08-33253ddab380,b0329bd7-fc45-4e83-993a-b73bd9d3549c,be4d9e85-dc53-4e70-90af-64d2d6b117d2
3,2017-07-03 17:40:05,3d6730ee-b869-47b7-90c6-1e074e4eb15b,3cade56a-6354-411a-82a6-f2c7774539c1,b0329bd7-fc45-4e83-993a-b73bd9d3549c,d43879d1-c424-4192-9eae-4537fa6687cb
4,2017-02-10 10:53:39,de4b3596-b4ab-47cd-b8ea-6f9e14170064,459e461d-a571-4ed3-8751-8f4cb5b9ff37,a7593a15-b93e-4bc3-91bf-e4074c931d33,61873fd7-f075-44c0-90fe-f6521226550d

In [4]:
# 각각의 id만 있는 table

In [5]:
app_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340730 entries, 0 to 340729
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   cdate             340730 non-null  datetime64[ns]
 1   company_uuid      340730 non-null  object
 2   job_uuid          340730 non-null  object
 3   user_uuid         340730 non-null  object
 4   application_uuid  340730 non-null  object
dtypes: datetime64[ns](1), object(4)
memory usage: 13.0+ MB

In [6]:
company_raw_df = pd.read_sql_table("Company", con=engine)
company_df = company_raw_df.copy()
company_df.head()

,cdate,mdate,found_date,employee_count,view_count,follow_count,reference_count,company_uuid
0,2022-06-09 04:08:40,2022-06-09 04:08:40,,0명,0,0,0,c46f2fa5-f940-40fb-bd4a-aa0ff7a837fd
1,2017-05-22 10:57:12,2022-07-25 00:12:02,,0명,256,0,0,725e87bb-de2f-416a-a6b8-1ca8d0d096e0
2,2017-11-14 11:42:55,2022-11-04 03:29:16,,0명,256,0,0,efa3747d-9bbd-4c84-af51-82ccf6545dcd
3,2017-11-27 10:59:30,2021-01-17 14:42:06,,0명,256,0,0,84aa2c20-d0f3-4ec3-ac06-1ef67e071b8f
4,2018-01-08 14:41:58,2022-07-25 01:34:16,2018-01-08,0명,256,0,0,761e76b3-507c-4c8f-b96f-fa47a8ccb5f2

In [7]:
company_addr_raw_df = pd.read_sql_table("CompanyAddress", con=engine)
company_addr_df = company_addr_raw_df.copy()
company_addr_df.head()

,name,company_uuid,address
0,,0bf81092-9bb5-44c7-a8de-e1db103253ef,서울 구로구
1,사무실,0bf81092-9bb5-44c7-a8de-e1db103253ef,서울특별시 구로구
2,,e8b24030-b0c5-4f07-9427-2d1e2519cb82,"158 Hoàng Hoa Thám, Phường 12, Tân Bình, Hồ Ch..."
3,,21743ac5-8957-4b2e-8f36-804d187d75a5,서울특별시 서초구
4,,82be7598-af6f-4af9-86d5-f57ccb76f8dd,서울특별시 종로구

In [8]:
log_22_raw_df = pd.read_sql_table("log_2022", con=engine)
log_22_df = log_22_raw_df.copy()
log_22_df.head()

,user_uuid,URL,timestamp,date,response_code,method
0,8a7e70cd-1630-4a8a-8303-0706af3a7908,api/search/language?name=한국어&_=1655915651225,2022-06-22 16:42:48.247454 UTC,2022-06-23,200,GET
1,8a7e70cd-1630-4a8a-8303-0706af3a7908,api/signup/form,2022-06-22 16:19:07.770741 UTC,2022-06-23,200,POST
2,8a7e70cd-1630-4a8a-8303-0706af3a7908,api/users/id/template,2022-06-22 16:41:54.449837 UTC,2022-06-23,200,POST
3,8a7e70cd-1630-4a8a-8303-0706af3a7908,api/users/id/template,2022-06-23 02:53:47.040932 UTC,2022-06-23,200,POST
4,8a7e70cd-1630-4a8a-8303-0706af3a7908,api/users/id/phone/verify/template?_=165591488...,2022-06-22 16:21:58.154299 UTC,2022-06-23,200,GET

In [9]:
acquisition =log_22_df['URL'].str.contains('signup/step3/done')

In [10]:
acquisition.sum()

np.int64(3135)

In [11]:
log_22_df.loc[acquisition, 'user_uuid'].nunique()

2762

In [12]:
log_22_df.loc[acquisition].head(100)

,user_uuid,URL,timestamp,date,response_code,method
53,8a7e70cd-1630-4a8a-8303-0706af3a7908,signup/step3/done,2022-06-22 16:20:49.307512 UTC,2022-06-23,200,GET
11953,7e92fb11-d00d-4db4-8574-bbba6355be6c,signup/step3/done,2022-06-12 06:25:55.224833 UTC,2022-06-12,200,GET
23786,343efc9a-2de4-4dd9-b04c-9eabeb185700,signup/step3/done,2022-05-30 13:11:35.740286 UTC,2022-05-30,200,GET
44239,998a4c65-5021-45a5-a8fb-7cc31aa49199,signup/step3/done,2022-12-17 16:34:35.697085 UTC,2022-12-18,200,GET
45866,998a4c65-5021-45a5-a8fb-7cc31aa49199,signup/step3/done,2022-12-17 16:34:48.037666 UTC,2022-12-18,200,GET
...,...,...,...,...,...,...
1317941,0c06bb59-9364-4532-9d50-64963ffa9bb5,signup/step3/done,2022-01-16 06:56:37.726011 UTC,2022-01-16,200,GET
1318017,0c06bb59-9364-4532-9d50-64963ffa9bb5,signup/step3/done,2022-04-11 16:27:31.267913 UTC,2022-04-12,200,GET
1320271,0277881d-20c8-4342-af37-4933c5501879,signup/step3/done,2022-06-26 11:48:13.978313 UTC,2022-06-26,200,GET
1337857,f4b88854-d1ae-4dfc-ac4a-8eb114cf37f9,signup/step3/done,2022-01-26 15:37:35.089349 UTC,2022-01-27,200,GET
1342687,a1cbdc09-1820-44f0-bc00-c68b3edf5164,signup/step3/done,2022-06-18 14:23:15.42189 UTC,2022-06-18,200,GET

In [13]:
log_22_df['user_uuid'].nunique()

17112

In [14]:
log_22_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10052895 entries, 0 to 10052894
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   user_uuid      object
 1   URL            object
 2   timestamp      object
 3   date           object
 4   response_code  object
 5   method         object
dtypes: object(6)
memory usage: 460.2+ MB

In [15]:
log_22_df['date'] = pd.to_datetime(log_22_df['date'], errors='coerce')

In [16]:
log_22_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10052895 entries, 0 to 10052894
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   user_uuid      object
 1   URL            object
 2   timestamp      object
 3   date           datetime64[ns]
 4   response_code  object
 5   method         object
dtypes: datetime64[ns](1), object(5)
memory usage: 460.2+ MB

In [17]:
log_22_df['timestamp'] = pd.to_datetime(log_22_df['timestamp'], errors='coerce')

In [18]:
log_22_df['timestamp'].min()

Timestamp('2021-12-31 15:00:00.532205+0000', tz='UTC')

In [19]:
# 22년 1월1일 이전의 Log들은 지우는게 나을듯: 확실한 분석을 위해서.

In [20]:
log_22_df = log_22_df[log_22_df['timestamp'] >= pd.Timestamp('2022-01-01', tz='UTC')]

In [21]:
log_22_df['timestamp'].min()

Timestamp('2022-01-01 00:00:06.855560+0000', tz='UTC')

In [22]:
log_22_df['timestamp'].max()

Timestamp('2022-12-31 14:59:16.695979+0000', tz='UTC')

In [23]:
log_23_raw_df = pd.read_sql_table("log_2023", con=engine)
log_23_df = log_23_raw_df.copy()
log_23_df.head()

,user_uuid,URL,timestamp,date,response_code,method
0,5ce8f5ca-3476-4623-a60c-00c98eef3b62,@user_id,2023-12-29 13:19:50.230356 UTC,2023-12-29,200,GET
1,5ce8f5ca-3476-4623-a60c-00c98eef3b62,api/users/notifications/mark_read?id=6425064&_...,2023-12-29 13:20:17.848762 UTC,2023-12-29,200,GET
2,5ce8f5ca-3476-4623-a60c-00c98eef3b62,jobs/id/id_title,2023-12-29 13:22:22.277796 UTC,2023-12-29,200,GET
3,5ce8f5ca-3476-4623-a60c-00c98eef3b62,suggest?q=epdlxj,2023-12-29 13:21:22.99993 UTC,2023-12-29,200,GET
4,5ce8f5ca-3476-4623-a60c-00c98eef3b62,api/current_guided_action/id,2023-12-29 13:20:19.834724 UTC,2023-12-29,200,POST

In [24]:
log_23_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7187383 entries, 0 to 7187382
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   user_uuid      object
 1   URL            object
 2   timestamp      object
 3   date           object
 4   response_code  object
 5   method         object
dtypes: object(6)
memory usage: 329.0+ MB

In [25]:
log_23_df['date'] = pd.to_datetime(log_23_df['date'], errors='coerce')
log_23_df['timestamp'] = pd.to_datetime(log_23_df['timestamp'], errors='coerce')

In [26]:
log_23_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7187383 entries, 0 to 7187382
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   user_uuid      object
 1   URL            object
 2   timestamp      datetime64[ns, UTC]
 3   date           datetime64[ns]
 4   response_code  object
 5   method         object
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), object(4)
memory usage: 329.0+ MB

In [27]:
log_23_df['timestamp'].min()

Timestamp('2022-12-31 15:00:08.173400+0000', tz='UTC')

In [28]:
log_23_df['user_uuid'].nunique()

15366

In [29]:
acquisition_23 =log_23_df['URL'].str.contains('signup/step3/done')

In [30]:
log_23_df.loc[acquisition_23, 'user_uuid'].nunique()

2030

In [31]:
# 2022_log 회원가입 완료 고객: 2762명 
# 2023_log 회원가입 완료 고객: 2030명

In [32]:
applying_22 =log_22_df['URL'].str.contains('api/jobs')
applying_23 =log_23_df['URL'].str.contains('api/jobs')

In [33]:
applying_22_df = log_22_df[applying_22]
applying_23_df = log_23_df[applying_23]

In [34]:
applying_df = pd.concat(
    [applying_22_df, applying_23_df],
    ignore_index=True
)

In [35]:
applying_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2998548 entries, 0 to 2998547
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   user_uuid      object
 1   URL            object
 2   timestamp      datetime64[ns, UTC]
 3   date           datetime64[ns]
 4   response_code  object
 5   method         object
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), object(4)
memory usage: 137.3+ MB

In [51]:
applying_users = applying_df['user_uuid'].nunique()
applying_users

17375

In [39]:
applying_df.head(100)

,user_uuid,URL,timestamp,date,response_code,method
0,8a7e70cd-1630-4a8a-8303-0706af3a7908,api/jobs/id/apply/step2,2022-06-22 16:46:28.394301+00:00,2022-06-23,200,POST
1,8a7e70cd-1630-4a8a-8303-0706af3a7908,api/jobs/id/apply/step1,2022-06-22 16:26:30.617417+00:00,2022-06-23,200,POST
2,8a7e70cd-1630-4a8a-8303-0706af3a7908,api/jobs/id/apply/step1,2022-06-22 16:34:10.840796+00:00,2022-06-23,200,POST
3,8a7e70cd-1630-4a8a-8303-0706af3a7908,api/jobs/id/other_jobs?offset=0&limit=5,2022-06-22 16:21:07.840124+00:00,2022-06-23,200,GET
4,8a7e70cd-1630-4a8a-8303-0706af3a7908,api/jobs/id/apply/step3,2022-06-22 17:00:39.065827+00:00,2022-06-23,200,POST
...,...,...,...,...,...,...
95,d7c84302-545f-4714-bcd1-0cc4328a0f89,api/jobs/id/apply/step4,2022-08-11 05:07:46.956963+00:00,2022-08-11,200,POST
96,d7c84302-545f-4714-bcd1-0cc4328a0f89,api/jobs/id/apply/step2,2022-08-11 05:02:30.740111+00:00,2022-08-11,200,POST
97,d7c84302-545f-4714-bcd1-0cc4328a0f89,api/jobs/id/apply/step4,2022-08-11 05:02:58.091756+00:00,2022-08-11,200,POST
98,d7c84302-545f-4714-bcd1-0cc4328a0f89,api/jobs/id/other_jobs?offset=0&limit=5,2022-08-11 04:56:24.131902+00:00,2022-08-11,200,GET
99,d7c84302-545f-4714-bcd1-0cc4328a0f89,api/jobs/id/apply/step4,2022-05-16 06:02:27.880902+00:00,2022-05-16,200,POST

In [40]:
applying_df['date'] = pd.to_datetime(applying_df['date'])

In [41]:
applying_df['timestamp'] = pd.to_datetime(applying_df['timestamp'])

In [42]:
applying_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2998548 entries, 0 to 2998547
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   user_uuid      object
 1   URL            object
 2   timestamp      datetime64[ns, UTC]
 3   date           datetime64[ns]
 4   response_code  object
 5   method         object
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), object(4)
memory usage: 137.3+ MB

In [47]:
# 지원 1단계 step 거친 user_uuid 
step_1 = applying_df['URL'].str.contains('api/jobs/id/apply/step1')
step_1_users = applying_df.loc[step_1, 'user_uuid'].nunique()
step_1_users

10781

In [48]:
# 지원 2단계 step 거친 user_uuid 
step_2 = applying_df['URL'].str.contains('api/jobs/id/apply/step2')
step_2_users = applying_df.loc[step_2, 'user_uuid'].nunique()
step_2_users

10665

In [49]:
# 지원 3단계 step 거친 user_uuid 
step_3 = applying_df['URL'].str.contains('api/jobs/id/apply/step3')
step_3_users = applying_df.loc[step_3, 'user_uuid'].nunique()
step_3_users

8890

In [50]:
# 지원 4단계 step 거친 user_uuid 
step_4 = applying_df['URL'].str.contains('api/jobs/id/apply/step4')
step_4_users = applying_df.loc[step_4, 'user_uuid'].nunique()
step_4_users

10222

In [53]:
# 도달율 구하기 
reach_rates = {
    "apply_step1": step_1_users / applying_users,
    "apply_step2": step_2_users / applying_users,
    "apply_step3": step_3_users / applying_users,
    "apply_step4": step_4_users / applying_users,
}

{ k: f"{v*100:.2f}%" for k, v in reach_rates.items() }

{'apply_step1': '62.05%',
 'apply_step2': '61.38%',
 'apply_step3': '51.17%',
 'apply_step4': '58.83%'}

In [ ]:
# 순차 퍼널 
step1_set = set(
    applying_df.loc[applying_df['URL'].str.contains('api/jobs/id/apply/step1'), 'user_uuid']
)

step2_set = set(
    applying_df.loc[applying_df['URL'].str.contains('api/jobs/id/apply/step2'), 'user_uuid']
)

step3_set = set(
    applying_df.loc[applying_df['URL'].str.contains('api/jobs/id/apply/step3'), 'user_uuid']
)

step4_set = set(
    applying_df.loc[applying_df['URL'].str.contains('api/jobs/id/apply/step4'), 'user_uuid']
)

####
strict_step2 = step1_set & step2_set
strict_step3 = strict_step2 & step3_set
strict_step4 = strict_step3 & step4_set

strict_counts = {
    "step1": len(step1_set),
    "step2": len(strict_step2),
    "step3": len(strict_step3),
    "step4": len(strict_step4),
}
strict_counts

{'step1': 10781, 'step2': 10650, 'step3': 8870, 'step4': 8741}

In [57]:
rates = {
    "step1_to_step2": {
        "conversion_rate": len(strict_step2) / len(step1_set),
        "drop_rate": 1 - (len(strict_step2) / len(step1_set)),
    },
    "step2_to_step3": {
        "conversion_rate": len(strict_step3) / len(strict_step2),
        "drop_rate": 1 - (len(strict_step3) / len(strict_step2)),
    },
    "step3_to_step4": {
        "conversion_rate": len(strict_step4) / len(strict_step3),
        "drop_rate": 1 - (len(strict_step4) / len(strict_step3)),
    },
}

pretty_rates = {
    k: {
        "conversion_rate": f"{v['conversion_rate']*100:.2f}%",
        "drop_rate": f"{v['drop_rate']*100:.2f}%",
    }
    for k, v in rates.items()
}

pretty_rates

{'step1_to_step2': {'conversion_rate': '98.78%', 'drop_rate': '1.22%'},
 'step2_to_step3': {'conversion_rate': '83.29%', 'drop_rate': '16.71%'},
 'step3_to_step4': {'conversion_rate': '98.55%', 'drop_rate': '1.45%'}}