In [15]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import yaml

In [23]:
with open("../config-local.yaml", "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

mysql_config = config["db"]
engine = create_engine(
    f"mysql+pymysql://{mysql_config['user']}:{mysql_config['password']}@{mysql_config['host']}:{mysql_config['port']}/{mysql_config['name']}?charset=utf8mb4"
)

pd.read_sql("SELECT 1 AS ok;", engine)

   ok
0   1

In [20]:
app_raw_df = pd.read_sql_table("Application", con=engine)
app_df = app_raw_df.copy()
app_df.head()

,cdate,company_uuid,job_uuid,user_uuid,application_uuid
0,2017-02-25 23:45:01,de4b3596-b4ab-47cd-b8ea-6f9e14170064,459e461d-a571-4ed3-8751-8f4cb5b9ff37,b0329bd7-fc45-4e83-993a-b73bd9d3549c,59c42363-f764-4cbd-aafd-20eb663ea5d7
1,2020-11-23 14:46:07,f6156b12-d4d7-469f-84be-31799c765211,e5ed4f4a-08aa-4f2d-9042-1e9bbd36803f,b0329bd7-fc45-4e83-993a-b73bd9d3549c,425db0e8-87f8-4b4d-8248-7f24c31d49d3
2,2017-10-28 22:30:11,2ed05b18-c735-474a-9faa-02095b25729a,0f636d7a-53f7-485e-8a08-33253ddab380,b0329bd7-fc45-4e83-993a-b73bd9d3549c,be4d9e85-dc53-4e70-90af-64d2d6b117d2
3,2017-07-03 17:40:05,3d6730ee-b869-47b7-90c6-1e074e4eb15b,3cade56a-6354-411a-82a6-f2c7774539c1,b0329bd7-fc45-4e83-993a-b73bd9d3549c,d43879d1-c424-4192-9eae-4537fa6687cb
4,2017-02-10 10:53:39,de4b3596-b4ab-47cd-b8ea-6f9e14170064,459e461d-a571-4ed3-8751-8f4cb5b9ff37,a7593a15-b93e-4bc3-91bf-e4074c931d33,61873fd7-f075-44c0-90fe-f6521226550d

In [24]:
# 각각의 id만 있는 table

In [25]:
app_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340730 entries, 0 to 340729
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   cdate             340730 non-null  datetime64[ns]
 1   company_uuid      340730 non-null  object
 2   job_uuid          340730 non-null  object
 3   user_uuid         340730 non-null  object
 4   application_uuid  340730 non-null  object
dtypes: datetime64[ns](1), object(4)
memory usage: 13.0+ MB

In [26]:
company_raw_df = pd.read_sql_table("Company", con=engine)
company_df = company_raw_df.copy()
company_df.head()

,cdate,mdate,found_date,employee_count,view_count,follow_count,reference_count,company_uuid
0,2022-06-09 04:08:40,2022-06-09 04:08:40,,0명,0,0,0,c46f2fa5-f940-40fb-bd4a-aa0ff7a837fd
1,2017-05-22 10:57:12,2022-07-25 00:12:02,,0명,256,0,0,725e87bb-de2f-416a-a6b8-1ca8d0d096e0
2,2017-11-14 11:42:55,2022-11-04 03:29:16,,0명,256,0,0,efa3747d-9bbd-4c84-af51-82ccf6545dcd
3,2017-11-27 10:59:30,2021-01-17 14:42:06,,0명,256,0,0,84aa2c20-d0f3-4ec3-ac06-1ef67e071b8f
4,2018-01-08 14:41:58,2022-07-25 01:34:16,2018-01-08,0명,256,0,0,761e76b3-507c-4c8f-b96f-fa47a8ccb5f2

In [27]:
company_addr_raw_df = pd.read_sql_table("CompanyAddress", con=engine)
company_addr_df = company_addr_raw_df.copy()
company_addr_df.head()

,name,company_uuid,address
0,,0bf81092-9bb5-44c7-a8de-e1db103253ef,서울 구로구
1,사무실,0bf81092-9bb5-44c7-a8de-e1db103253ef,서울특별시 구로구
2,,e8b24030-b0c5-4f07-9427-2d1e2519cb82,"158 Hoàng Hoa Thám, Phường 12, Tân Bình, Hồ Ch..."
3,,21743ac5-8957-4b2e-8f36-804d187d75a5,서울특별시 서초구
4,,82be7598-af6f-4af9-86d5-f57ccb76f8dd,서울특별시 종로구

In [30]:
company_addr_df['address'].nunique()

528

In [31]:
company_addr_df['address'].unique()

array(['서울 구로구', '서울특별시 구로구',
       '158 Hoàng Hoa Thám, Phường 12, Tân Bình, Hồ Chí Minh, 베트남',
       '서울특별시 서초구', '서울특별시 종로구', '서울특별시 강남구', '수원시', '서울특별시 마포구', '제주시',
       '서울특별시 광진구', '서울특별시 동대문구', '서울특별시 용산구',
       'Main Building, University Street, National University of Mongolia, Ulaanbaatar 14201, Mongolia',
       'Baga Toiruu-20, P.O.Box 349, Ulaanbaatar 210646 몽고', '서울특별시 관악구',
       '고양시 동구', '서울특별시 중구', '부산광역시 영도구', '서울특별시 금천구', '용인시', '성남시',
       '서울특별시 성동구', '대전광역시 유성구', '포항시 남구', '경상남도 하동군', '고양시 서구', 'Seoul',
       '서울특별시 영등포구', '서울특별시 강서구', '서울특별시 서대문구', '서울특별시 송파구', '안산시',
       '미국 뉴욕 뉴욕', '영국 런던',
       '11/17 Soi Ruam Ruedi, Khwaeng Lumphini, Khet Pathum Wan, Krung Thep Maha Nakhon 10330 태국',
       '싱가포르', '서울특별시', '서귀포시', '부산광역시 금정구', '시흥시', '화성시', '서울특별시 양천구',
       '오산시', '대구광역시 동구', '천안시 남구', '미국 일리노이 시카고',
       '1450 2nd St, Santa Monica, CA 90401 미국',
       '400 Fang Chun Lu, Pudong Xinqu, Shanghai Shi, 중국',
       '1-chōme-6-5 Jinnan, Shibuya City, Tokyo 150-0041 일본', '서울 강남구',
       '울산광역시 울주군', '안성시', '서울특별시 노원구', '서울특별시 강북구', '의정부시',
       '미국 캘리포니아 뉴포트비치', '부천시', '3003 N 1st St, San Jose, CA 95134 미국',
       '천안시 북구', '광주광역시 서구',
       'Jl. TB Simatupang No.Kav. 88, RT.1/RW.1, Kebagusan, Kec. Ps. Minggu, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12520 인도네시아',
       'Jalan Kebagusan 1 Kav. 6, Kebagusan, Pasar Minggu, RT.2/RW.1, Kebagusan, Kec. Ps. Minggu, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12520 인도네시아',
       '인천광역시 연수구', '845 Market St, San Francisco, CA 94103 미국', '고양시',
       '여수시', '울산광역시 북구', '40 Boardman Pl, San Francisco, CA 94103 미국',
       'C - 20, G Block, Bandra Kurla Complex, G Block BKC, Bandra Kurla Complex, Bandra East, Mumbai, Maharashtra 400051 인도',
       '서울특별시 은평구', '안양시', '베트남 Hanoi, 호안끼엠 하노이', '전라북도 완주군', '부산광역시 남구',
       '제천시', '서울특별시 동작구', '경주시', '아산시', '체코', '의왕시', '인천광역시 남구',
       '인천광역시 강화군', '인천광역시 서구', '당진시', '구리시', '하남시', '부산광역시 강서구',
       '부산광역시 수영구', '광주시', '태백시', '대구광역시 달성군', '충청북도 단양군', '부산광역시 해운대구',
       '대전광역시 서구', '광명시', '대구광역시 서구', 'W 47th St, New York, NY 10036 미국',
       '부산 해운대구', '광주광역시 동구', '444 Castro St, Mountain View, CA 94041 미국',
       '10 Cyberport Rd, Telegraph Bay, 홍콩', '미국 92801 캘리포니아 애너하임',
       '인천광역시 동구', '남양주시', '서울특별시 강동구', '이천시', '인천광역시 계양구', '서울특별시 도봉구',
       '울산광역시 동구', 'Tanjong Katong Rd S, 싱가포르', '춘천시', '부산광역시 동래구', '과천시',
       '군산시', '주소', '싱가포르 싱가포르', '54 W 40th St, New York, NY 10018 미국',
       '서울특별시 성북구', '영천시', '부산광역시 동구', '울산광역시 남구', '부산광역시', '서울 마포구',
       'Huike Rd, Jinnan Qu, Tianjin Shi, 중국 300350', '인천광역시 부평구',
       'Gumi 1(il)-dong Bundang-gu Соннам Кёнгидо Южная Корея, Gumi 1(il)-dong, Bundang-gu, Seongnam-si, Gyeonggi-do',
       '대구광역시 수성구', '대구광역시 북구', '구미시', '충청남도', '충주시', '광주광역시 북구',
       '인천광역시 중구', '군포시', '평택시', '논산시', '충청북도', '김포시', '인천광역시',
       '부산광역시 부산진구', '경기도 양평군', '대구광역시 중구', '창원시',
       '6, Jiphyeonjungang, Sejong-si', '대전광역시 중구', '미국 조지아 애틀랜타', '경기도',
       '미국 캘리포니아 벌링게임', '충청남도 예산군',
       'Danneskiold-Samsøes Allé 41, 1434 København K, 덴마크', '대한민국',
       '3580 Wilshire Blvd, Los Angeles, CA 90010 미국', '서울시 관악구',
       '인도네시아 자카르타라야 자카르타',
       '2 Chome-20-13 Taitō, Taitō-ku, Tōkyō-to 110-0016 일본',
       '〒150-0002, 일본', '파주시', '미국 캘리포니아 마운틴뷰',
       'STATION, 5 Parvis Alan Turing, 75013 Paris, 프랑스', '광주광역시 남구',
       '6 Chome-11-1 Roppongi, Minato-ku, Tōkyō-to 106-6108 일본',
       '강원도 평창군', '서울 중랑구', '충청북도 진천군', '서울특별시 중랑구',
       '555 W 5th St, Los Angeles, CA 90013 미국',
       '11 Rue Carnot, 94270 Le Kremlin-Bicêtre, 프랑스', '대전광역시 대덕구', '익산시',
       '순천시', '부산광역시 북구', '부산광역시 사상구', '김해시', '진주시', '천안시',
       '8751 Paseo de Roxas, Makati, 1227 Metro Manila, 필리핀',
       'AIA Central, Lv 31, Jl. Jend. Sudirman, RT.5/RW.4, Karet Semanggi, Jakarta, South Jakarta City, Jakarta 12930 인도네시아',
       '대구광역시 남구', '전라남도 무안군', '미국 캘리포니아 산호세', '세종',
       '16350 Valley Oaks Estates Ct, Wildwood, MO 63005 미국', '부산광역시 사하구',
       '대구광역시', '울산광역시 중구', '전주시', '일본', '세종특별자치시', '대전광역시', '원주시',
       '태국 방콕', '16755 Von Karman Ave, Irvine, CA 92606 미국',
       '200 Spectrum Center Dr, Irvine, CA 92618 미국', '충청북도 음성군',
       'E Poultry Ave, Farringdon, London EC1A 9PT 영국', '부산광역시 서구',
       '34 Lê Duẩn, Bến Nghé, Quận 1, Hồ Chí Minh 700000 베트남',
       '중국 산둥 성 칭다오 시 청양 구', '114 Lavender St, Singapore 338729',
       '싱가포르 038985', '경산시', '강원도 고성군', '대전광역시 동구', '양산시',
       '80 Raffles Pl, 싱가포르 048624',
       '55 University Ave Suite 800, Toronto, ON M5E 1S2 캐나다',
       '부산광역시 연제구',
       '1 Song Hành, An Phú, Quận 2, Thành phố Hồ Chí Minh, 베트남', '목포시',
       '1 Broadway, Cambridge, MA 02142 미국', '통영시', '경상북도 칠곡군',
       '충청남도 홍성군', '충청북도 영동군', '나주시', '충청남도 서천군', '남원시', '청주시',
       '부산광역시 중구', '경상남도 창녕군', '강릉시', '김천시', '미국 델라웨어', '충청북도 괴산군', '세종시',
       '광주광역시 광산구', 'Duncan St, Islington, London N1 영국', '중국 상하이 시 상하이시',
       '68 Phố Nguyễn Cơ Thạch, Mỹ Đình, Từ Liêm, Hà Nội, 베트남',
       '2 Yamashitachō, Naka Ward, Yokohama, Kanagawa 231-0023 일본',
       'Scbd, Jl. Jend. Sudirman No.52-53, RT.5/RW.3, Senayan, Jakarta, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12190 인도네시아',
       '경상북도 영덕군', '양주시',
       '284, 41/2 Lý Thường Kiệt, Phường 7, Quận 10, Thành phố Hồ Chí Minh 700000 베트남',
       '포천시', '인천광역시 미추홀구',
       'H3J5+5PR, Lourdes, San Antonio, Pasig, Metro Manila, 필리핀',
       'Tòa nhà Mitec, Yên Hoà, Cầu Giấy, Hà Nội, 베트남',
       'Mansion Oka, 1-chōme-11-8 Yushima, Bunkyo City, Tokyo 113-0034 일본',
       '부산광역시 기장군', '강원도 홍천군',
       '2 Chome-16 Konan, Minato City, Tokyo 108-0075 일본',
       '1035 Yee Kuk W St, Cheung Sha Wan, 홍콩',
       '3-chōme-13-10 Nishiazabu, Minato City, Tokyo 106-0031 일본',
       '10 Anson Rd, 싱가포르 079903',
       '479 Jessie St, San Francisco, CA 94103 미국',
       '107 S Railroad Ave, San Mateo, CA 94401 미국', '미국 캘리포니아 샌프란시스코',
       '미국 뉴욕', '460 Park Ave, New York, NY 10022 미국', '서울 영등포구',
       '서울 관악구',
       '228 Park Ave S #42010 New York, NY 10003-1502 228 Park Ave ',
       '서울 서초구', '서울시 서초구', '서울 송파구', '서울 강동구', '서울 용산구', '대전 유성구',
       '서울시 강남구', '서울 금천구', '서울 광진구', '서울 중구', '서울 성동구', '서울 양천구',
       '서울 종로구', '서울시 중구', '서울 서대문구', '경기 양평군 강상면', 'NEW YORK, NY',
       '인천시 서구',
       '530 Howard Street, Suite 370, San Francisco, CA, 94105, U.S.',
       '서울 동작구', '서울 강서구', '서울시 송파구', '서울시 노원구', '대구 북구', '서울 은평구',
       '서울 동대문구', '인천 남구', '서울 성북구', '부산 부산진구', '부산 북구', '인천 부평구',
       '인천 계양구', '인천 연수구', '서울시 영등포구', '대구 남구', '인천 중구', '광주 서구',
       '서울시 성동구', '부산시 연제구', '인천 동구', '대구 중구',
       'Flow State Media 533 Airport Blvd #400 Burlingame, CA 94010  ',
       'Varazo, Inc. 2635 North 1st St., Suite 242 San Jose, CA 95134',
       '대전 서구', 'Koto-ku, Tokyo, 1350064, Japan', '대구 동구', '광주 북구',
       '서울 강북구',
       '6 Chome-6-3 Nishishinjuku, Shinjuku-ku, Tōkyō-to 160-0023 ',
       '울산 남구', '71 Ayer Rajah Cresent, Singapore', '부산 동래구', '서울 노원구',
       '인천 서구', '150 Lucius Gordon Dr, West Henrietta, NY 14586 ',
       '1901 S Bascom Ave, Campbell, CA 95008 미국', '서울시 동대문구', '울산광역시',
       '〒158-0094, 일본',
       'Jl. Permata Hijau Blok B No.8, RT.4/RW.2, Grogol Utara, Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12210 인도네시아',
       '19 Wang Hoi Rd, Kowloon Bay, 홍콩', '베트남', '부산 금정구', '동두천시',
       '중국 베이징 시 베이징', '미국 캘리포니아 어바인',
       'Phùng Văn Cung, Phú Nhuận, Hồ Chí Minh, 베트남', '구리시 동구', '사천시',
       '전라남도 곡성군', '2 Changi Business Park Cres, 싱가포르 486029',
       '500 Yale Ave N, Seattle, WA 98109 미국',
       '17777 Center Ct Dr N, Cerritos, CA 90703 미국',
       '태국 20150 촌 부리 방라뭉 파타야',
       '16188 Mariner Dr, Huntington Beach, CA 92649 미국',
       '오스트레일리아 뉴사우스웨일스 주 시드니', 'Hanoi, 베트남', '일본 도쿄도',
       '일본 〒150-6018 Tōkyō-to, Shibuya-ku, Ebisu, 4 Chome−20−２０番', '미국',
       '175 Varick St, New York, NY 10013 Floor 3',
       '409 Bundy Ave, San Jose, CA 95117 미국',
       'Omlaat Street - Trade Centre - DIFC - Dubai - 아랍에미리트',
       '100 Cyberport Rd, Telegraph Bay, 홍콩',
       '8 Kallang Ave, Singapore 339509', '불가리아 소피아', '미국 캘리포니아 샌타클래라',
       '400 Concar Dr, San Mateo, CA 94402 미국',
       '68 Yu Yuan Lu, Jing An Si, Jingan Qu, Shanghai Shi, 중국 200023',
       '25 Anson Rd, 싱가포르 079903', '미국 캘리포니아 웨스트할리우드',
       '57 Wireless Road Khwaeng Lumphini, Khet Pathum Wan, Krung Thep Maha Nakhon 10330 태국',
       '298 5th Ave, New York, NY 10001 미국',
       '1178 Broadway, New York, NY 10001 미국',
       '1382 Valencia Ave, Tustin, CA 92780 미국',
       '700 Airport Blvd, Burlingame, CA 94010 미국', '경상북도 울진군',
       '222 Pacific Coast Hwy 10th floor, El Segundo, CA 90245 미국',
       '중국 상하이 시 민항 구',
       '2 Chome-33-８ Ebisu, Shibuya-ku, Tōkyō-to 150-0013 일본',
       'Han He Lu, Haidian Qu, Beijing Shi, 중국',
       'Aske Stables, Richmond DL10 5HG 영국', '일본 도쿄도 도쿄',
       '630 8th St, San Francisco, CA 94103 미국',
       '3 Chome-15 Nishigotanda, Shinagawa, Tokyo 141-0031 일본',
       '미국 11356 뉴욕 칼리지 포인트',
       '20 Primrose St, Broadgate, London EC2M 3AF 영국',
       '5870 Greenwood Rd, Shreveport, LA 71119 미국', 'No need',
       '1 Chome-9-6 Jingūmae, Shibuya-ku, Tōkyō-to 150-0001 일본',
       '미국 10011 뉴욕 뉴욕', '우크라이나 02000 Kyiv city, 키예프',
       'Yau Lee Centre, 45 Hoi Yuen Rd, Kwun Tong, 홍콩',
       '268 Trần Hưng Đạo B, Phường 11, Quận 5, Thành phố Hồ Chí Minh 700000 베트남',
       '111 Somerset Rd, 싱가포르 238164',
       '8-18 Nakamachi, Naka-ku, Hiroshima-shi, Hiroshima-ken 730-0037 일본',
       '미국 20876 메릴랜드 제르맨타운',
       '일본 〒105-0004 Tōkyō-to, Minato-ku, Shinbashi, 5 Chome−１７ 港新ビル ２ 丁目 １７',
       '15260 Ventura Blvd, Sherman Oaks, CA 91403 미국',
       '6701 Democracy Blvd, Bethesda, MD 20817 미국',
       '1234 6th St, Santa Monica, CA 90401 미국', '대만',
       '706 Winslow St, Redwood City, CA 94063 미국', '상주시',
       'Mazaya Business Avenue BB2 - دبي - 아랍에미리트', '중국 산둥성 옌타이시',
       'Vinhomes Central Park, Phường 22, Bình Thạnh, Ho Chi Minh City, 베트남',
       '1 Ratchadaphisek Rd, Din Daeng, Krung Thep Maha Nakhon 10400 태국',
       '말레이시아', '서울시 마포구', '광주광역시', '미국 캘리포니아 샌머테이오',
       '101 California St, San Francisco, CA 94111 미국', '미국 캘리포니아 버클리',
       '1952 Gallows Rd, Vienna, VA 22182 미국', '경상남도 함양군', '광양시',
       '중국 Guangdong Sheng, Shenzhen Shi, Baoan Qu, 新安三路', '포항시 북구',
       '51 Cuppage Rd, 싱가포르 229469',
       '3435 Wilshire Blvd, Los Angeles, CA 90010 미국', '인도 카르나타카 벵갈루루',
       '83 Clemenceau Ave, 싱가포르 239920', '독일',
       '50 Mawson Lakes Blvd, Mawson Lakes SA 5095 오스트레일리아', '충청남도 금산군',
       '3500 W 6th St #238, Los Angeles, CA 90020 미국',
       'Section 2, Anhe Road, Da’an District, Taipei City, 대만 106',
       '1 Chome-4-5 Roppongi, Minato-ku, Tōkyō-to 106-0032 일본',
       '535 Jaffe Rd, Causeway Bay, 홍콩', '71 Robinson Rd, 싱가포르 068895',
       '충청남도 부여군', '3 Fraser St, 싱가포르 189352',
       'Shalimar Huda City Center, Delhi, Sector 29, Gurugram, Haryana 122007 인도',
       '3340 Ocean Park Blvd, Santa Monica, CA 90405 미국',
       '10 Anson Rd, Singapore 079903', 'Von Karman Ave, Irvine, CA, 미국',
       '6, 1st A Cross Rd, 7th Block, Koramangala, Bengaluru, Karnataka 560030 인도',
       '2811 Mission College Blvd, Santa Clara, CA 95054 미국', '인도',
       '일본 〒160-0023 도쿄도 신주쿠구 니시신주쿠',
       '90 N Sathon Rd, Khwaeng Silom, Khet Bang Rak, Krung Thep Maha Nakhon 10500 태국',
       '810 Quayside Dr, New Westminster, BC V3M 6B9 캐나다',
       '9 Temasek Blvd, 싱가포르',
       '217 N Harbor Blvd, Fullerton, CA 92832 미국',
       '93 Lockhart Rd, Wan Chai, 홍콩',
       '276 5th Ave, New York, NY 10001 미국',
       '600 Congress Ave, Austin, TX 78701 미국',
       '696 Wei Hai Lu, Jingan Qu, Shanghai Shi, 중국 200085',
       '6650 W Touhy Ave, Niles, IL 60714 미국', '속초시',
       '10 Corporate Park, Irvine, CA 92606 미국', '전라남도 보성군',
       'Cyberport 3, Telegraph Bay, 홍콩',
       '인도네시아 요그야카르타 Yogyakarta City, 족자카르타', '전라북도 부안군', '슬로바키아 브라티슬라바',
       'Office 24, 46 Lower Richmond Rd., London SW15 1JP 영국',
       '353 W 48th St, New York, NY 10036 미국', '거제시',
       '17875 Von Karman Ave, Irvine, CA 92614 미국',
       '1863 Concourse Dr, San Jose, CA 95131 미국',
       '7094 Miratech Dr suite 110, San Diego, CA 92121 미국', '영주시',
       '프랑스 파리', '서울시 금천구', '인천시 남구', '서울시 종로구', '대구시 북구', '구미시 북구',
       '울산시 남구', '서울시 구로구',
       'Water Strider Inc. 3587 Lupine Avenue Palo Alto, CA 94303.',
       '여주시', '서울시 용산구', '서울시 강서구', '440N wolfe Rd, Sunnyvale, CA 94085',
       '上海市閔行區万源路2158 号泓毅大厦901室', '대구시 동구', '대구시 서구', '전북 진안군 마령면 널티로 23',
       '대전시 유성구', '문경시', '부산 남구', '관악대로 480, 802호(관양동, 우정타운)', '부산 동구',
       '8-5, Ulaanbaatar, 몽고', 'Leipziger Str. 126, 10117 Berlin, 독일',
       '201 Mission St, San Francisco, CA 94105 미국',
       '3990 Freedom Cir, Santa Clara, CA 95054 미국',
       '6253 Hollywood Blvd, Los Angeles, CA 90028 미국',
       '2 Orchard Link, 싱가포르 237978',
       'Level 2, Menara Dana 13, Jalan PJU 1a/46, Pusat Perdagangan Dana 1, 47301 Petaling Jaya, Selangor, 말레이시아',
       '1830 Harrison St, San Francisco, CA 94103 미국',
       '21 New St, Burwood NSW 2134 오스트레일리아', '안동시',
       'Kelana Square, 17, Jalan SS 7/26, Dataran Usahawan Kelana Square, 47301 Petaling Jaya, Selangor, 말레이시아',
       '1050 30th St NW, Washington, DC 20007 미국',
       '12655 W Jefferson Blvd, Los Angeles, CA 90066 미국',
       '6, Jl. Sultan Iskandar Muda No.10, RT.10/RW.6, Kby. Lama Utara, Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12240 인도네시아',
       'Colsmanstraße 9, 45257 Essen, 독일', '독일 노르트라인 베스트팔렌',
       '440 N Wolfe Rd, Sunnyvale, CA 94085 미국', '대한민국 홍성군',
       '690 Saratoga Ave, San Jose, CA 95129 미국',
       '8 Marina View, 싱가포르 018960',
       '9 Bùi Viện, Quận 1, Hồ Chí Minh, 베트남',
       'San Jose, California 95134 ', '3003 N. 1st Street, Suite 302 ',
       'San Francisco, California 94108',
       'Suite 704 109 Pitt St Sydney Australia 2000', '캐나다 온타리오 토론토',
       '미국 캘리포니아 팰로앨토', '중국', '인도네시아', '영국', '브라질', '아랍에미리트 두바이', '캐나다',
       '프랑스', '이탈리아', '150 Beach Rd, #22 01 08 Gateway West, 싱가포르 189720',
       '10404 6th St, Rancho Cucamonga, CA 91730 미국', '홍콩',
       '16 Washington Pl, New York, NY 10003 미국',
       '5460 Fairmont Dr, Wilmington, DE 19808 미국',
       'Heinestraße 21, 1020 Wien, 오스트리아',
       'Via F.lli Piazza, 42, 20012 Cuggiono MI, 이탈리아',
       '3rd floor, 9 Devonshire Square, London EC2M 4YD 영국',
       '213 Rue du Diamant, 40600 Biscarrosse, 프랑스',
       'Strada Statale 195 Sulcitana, 09123 Cagliari CA, 이탈리아',
       'Carrer de Ramon Turró, 169, A, 08005 Barcelona, 스페인',
       '450 Townsend St, San Francisco, CA 94107 미국',
       '929 Colorado Ave, Santa Monica, CA 90401 미국',
       '2-chōme-22-1 Nishishinbashi, Minato City, Tōkyō-to 105-0003 일본',
       '548 Market St, San Francisco, CA 94104 미국', '독일 베를린',
       'Großer Burstah 46-48, 20457 Hamburg, 독일', '미국 캘리포니아',
       '222 Broadway #19101, New York, NY 10038 미국',
       '10 Rue Ponscarme, 75013 Paris, 프랑스',
       'aleja Grunwaldzka 472B, 80-309 Gdańsk, 폴란드', '강원도 양양군',
       'Jingmao 2nd Rd, Nangang District, Taipei City, 대만 115',
       '베트남 Ho Chi Minh City, 호치민',
       '5 Parvis Alan Turing, 75013 Paris, 프랑스',
       '1262 Euclid Ave SE, Cleveland, TN 37311 미국',
       '344 20th St, Oakland, CA 94612 미국',
       '일본 〒142-0051 도쿄 도 시나가와 구 히라쓰카',
       'Dubai Al-Ain Road (Route 66) - Dubai - 아랍에미레이트',
       '140 Paya Lebar Rd, AZ @ Paya Lebar, Singapore 409015',
       'Via Laietana, 52, 08003 Barcelona, 스페인',
       '655 Knight Way, Stanford, CA 94305 미국',
       'P. Trung Kính, Trung Hoà, Cầu Giấy, Hà Nội, 베트남', '전라남도 고흥군'],
      dtype=object)